### ISSUE TITLE
Possible to publish to Ansible Galaxy

### ISSUE THREAD

**Issue by amaltson** [mdklatt/ansible-tmpdir-role#3]
Not sure if this has been requested before, but is there a chance you could push this to Ansible Galaxy? Thanks!

**Comment by mdklatt** [comment]
I took a look at publishing this on Galaxy awhile ago, and I'll have to make some tweaks. For example, I'm not sure if Galaxy supports reStructuredText for READMEs. 

If you weren't aware, `ansible-galaxy` can install roles directly from GitHub (GitLab, etc.) as well. Put this in your `requirements.yml` file:
```
- name: tmpdir 
  src: "https://github.com/mdklatt/ansible-tmpdir-role"
  version: v0.2.0

```

**Comment by amaltson** [comment]
Yep, that's the way I consumed it currently. Anyway, just a suggestion 😉

**Comment by mdklatt** [comment]
This role is now available on [Ansible Galaxy](https://galaxy.ansible.com/mdklatt/tmpdir).
